---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R hooks $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R types $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH
    - /bin/cp next.config.mjs $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp postcss.config.mjs $DEPLOYPATH
    - /bin/cp tailwind.config.ts $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH 