---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/a
    # Create directory and clean up
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/node_modules
    - /bin/rm -rf $DEPLOYPATH/.next
    # Copy project files
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R hooks $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R types $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.mjs $DEPLOYPATH
    - /bin/cp postcss.config.mjs $DEPLOYPATH
    - /bin/cp tailwind.config.ts $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
    # Create application entry point
    - /bin/echo '{"scripts":{"start":"next start","build":"next build"},"dependencies":{"next":"latest","react":"latest","react-dom":"latest"}}' > $DEPLOYPATH/package.json
    # Create a .htaccess file for routing
    - /bin/echo "DirectoryIndex disabled" > $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteEngine On" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteRule ^$ http://localhost:3000/ [P,L]" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteCond %{REQUEST_FILENAME} !-f" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteCond %{REQUEST_FILENAME} !-d" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteRule ^(.*)$ http://localhost:3000/$1 [P,L]" >> $DEPLOYPATH/.htaccess
    # Create an empty .env file (you'll need to fill this manually in cPanel)
    - /bin/touch $DEPLOYPATH/.env 